<?php
include("header.php");
?>
<link type="text/css" rel="stylesheet" href="stylesheet.css" />

		<div class="news">
			<h2><a href="">Lorem Ipsum</a></h2>
			<p class="date">Oct 26, 2013</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in eros sodales, fringilla mi eget, malesuada lacus. Cras sit amet urna quis nulla vestibulum porta. Integer massa massa, faucibus eget sapien at, fringilla porttitor elit. Praesent venenatis massa neque, ac iaculis elit aliquet ac. Curabitur eget tempus leo. Maecenas non velit non dui varius lacinia. Fusce id volutpat dui, in volutpat nibh. Nam nulla ligula, porta id ipsum vel, laoreet blandit felis. Duis et urna blandit, ullamcorper nisi ut, posuere erat. In adipiscing, elit sodales posuere semper, orci ligula convallis arcu, in malesuada felis orci a lorem. Nullam ultrices mauris sed mi porttitor vestibulum sit amet vitae justo. Proin vitae fermentum libero, a volutpat mauris. Maecenas eleifend scelerisque odio. Donec aliquet, massa non consectetur tincidunt, lacus lacus fermentum lorem, id adipiscing augue enim vel lectus. Duis molestie faucibus ipsum, non commodo erat laoreet feugiat.</p>
			<p>Nullam blandit sollicitudin erat, id faucibus nisi hendrerit quis. Praesent eleifend dui neque, ut ornare est malesuada ut. Ut ut vestibulum justo. Quisque quis ornare urna. Nullam mollis tristique felis vel lobortis. Suspendisse fermentum diam mi, vel consectetur nisi scelerisque sed. Proin auctor eget est eget congue.</p>
			<p>Nunc non lectus risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce pellentesque sagittis vulputate. Vivamus leo nisl, blandit suscipit condimentum congue, condimentum dignissim leo. Nullam sodales pulvinar auctor. Sed vel nibh metus. Nam a accumsan nisl./p>
			<p>Fusce fringilla purus vitae sollicitudin mollis. Ut mollis tincidunt ante sit amet luctus. Mauris eu ante feugiat turpis auctor fringilla. Ut eu orci vehicula, adipiscing nunc ac, accumsan libero. Ut et ultrices felis. Curabitur facilisis, leo nec tincidunt vulputate, erat purus porta urna, eget iaculis quam lorem eu sem. Sed scelerisque tellus quis ultricies elementum. Phasellus nisl mauris, fringilla bibendum gravida ut, consequat vitae quam. Proin ligula velit, dapibus eu arcu a, malesuada aliquam eros. Pellentesque tortor eros, blandit ut lacus a, ultricies feugiat velit.</p>
			<p>Aenean porta rhoncus nunc, nec vestibulum odio convallis quis. Proin turpis enim, rutrum ut lacinia non, pharetra eu ligula. Praesent posuere, tortor a scelerisque iaculis, magna ante aliquam orci, et gravida tellus quam quis felis. Nulla facilisi. Cras velit felis, elementum ut dolor at, tincidunt facilisis augue. Aliquam erat volutpat. Aenean nec quam metus. Quisque mattis sem vitae eros condimentum iaculis. Suspendisse quis semper mi. Suspendisse porta, ipsum in congue varius, enim risus semper quam, ac gravida nisi sem vel augue. Sed fermentum pharetra nibh ac fermentum. Pellentesque non ornare augue. Curabitur vehicula odio ut urna rhoncus, a placerat magna porta. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
			<p>Aenean sodales, neque et commodo porta, arcu velit consectetur arcu, eget dignissim velit dui ultrices ligula. Cras ac nibh dolor. Nullam mollis rutrum auctor. Donec aliquam, magna at dignissim aliquam, est quam iaculis arcu, at semper lorem erat ut nulla. Suspendisse potenti. Phasellus semper vestibulum erat, suscipit dictum quam consectetur vitae. Phasellus tempor, nisi sed suscipit porta, magna magna elementum ipsum, id ultrices ante nisi eu risus. Donec aliquam elit a lorem varius, ac rhoncus nibh volutpat.</p>
			<p>Phasellus ut turpis at tortor accumsan semper. Duis blandit, magna congue semper fermentum, quam justo sagittis metus, ut rhoncus erat nisi sed arcu. Phasellus in risus semper, convallis metus ut, imperdiet quam. Donec aliquam eget libero vitae venenatis. Quisque nec dictum ipsum, non mollis massa. Sed vestibulum gravida nisl, sit amet varius tortor rutrum quis. Aliquam blandit metus a varius tristique. Integer egestas ac diam at auctor. Nam congue pulviuam vel faucibus. Ut ac pellentesque erat, eu ultrices lacus. Praesent elit velit, ultricies nec pharetra at, fringilla non tellus. Integer nibh lectus, dignissim id placerat quis, ornare ut dui. Vestibulum sodales a est et sagittis. Nam tincidunt mattis turpis lobortis faucibus.</p>
			<p>Morbi laoreet rhoncus elit, sit amet aliquet justo mattis a. Donec id sodales mi, eget feugiat orci. Mauris ac iaculis mi. Duis vitae tempor ligula. Suspendisse luctus turpis eu enim interdum blandit. Fusce nec lobortis lectus. Donec rhoncus sagittis urna, quis vulputate justo ornare eu. Donec fringilla metus lobortis, commodo elit vel, aliquet tortor. In fermentum ultrices blandit. Phasellus commodo non quam eu tincidunt. Proin et molestie turpis. Nullased augue justo. Pellentesque hendrerit eros vel massa porta posuere. Ut faucibus pretium mauris quis semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum metus lectus, blandit a felis sit amet, volutpat pretium eros.</p>
			<p>Vivamus a sollicitudin tellus, et molestie nunc. Suspendisse rhoncus enim ante, quis cursus quam faucibus nec. Suspendisse potenti. Ut quis felis at purus faucibus pharetra. Aliquam erat volutpat. Praesent vestibulum nisi sit amet libero gravida porta. Etiam metus velit, dignissim vitae dignissim a, viverra vitae est. Duis imperdiet congue libero, id hendrerit tellus. Sed erat diam, porta facilisis massa eget, mattis hendrerit augue. Sed sed congue nisl.</p>
			<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque tristique pellentesque est, a tempus libero molestie eget. Phasellus feugiat velit ac est sollicitudin molestie. Curabitur nec risus nunc. Aliquam erat volutpat. Vestibulum egestas justo sed bibendum sodales. Pellentesque id felis risus. Pellentesque euismod quis massa sed consectetur. Mauris at tempor urna. Phasellus ullamcorper ante vitae auctor dictum. Aliquam ut sollicitudin ipsum. Aliquam vitae purus vel urna eleifend ultricies. Vestibulum commodo sed metus in pretium. Vestibulum consequat metus ac mi blandit, eget dapibus massa blandit. Sed eget lobortis massa.</p>
			
			<div class="news_foot">
				<span><a href="">Commentaire</a></span>
				<span class="author">Publie par Op</span>
			</div>
			
		</div>	

		<div class="news">
			<h2><a href="">Lorem Ipsum</a></h2>
			<p class="date">Oct 26, 2013</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in eros sodales, fringilla mi eget, malesuada lacus. Cras sit amet urna quis nulla vestibulum porta. Integer massa massa, faucibus eget sapien at, fringilla porttitor elit. Praesent venenatis massa neque, ac iaculis elit aliquet ac. Curabitur eget tempus leo. Maecenas non velit non dui varius lacinia. Fusce id volutpat dui, in volutpat nibh. Nam nulla ligula, porta id ipsum vel, laoreet blandit felis. Duis et urna blandit, ullamcorper nisi ut, posuere erat. In adipiscing, elit sodales posuere semper, orci ligula convallis arcu, in malesuada felis orci a lorem. Nullam ultrices mauris sed mi porttitor vestibulum sit amet vitae justo. Proin vitae fermentum libero, a volutpat mauris. Maecenas eleifend scelerisque odio. Donec aliquet, massa non consectetur tincidunt, lacus lacus fermentum lorem, id adipiscing augue enim vel lectus. Duis molestie faucibus ipsum, non commodo erat laoreet feugiat.</p>
			<p>Nullam blandit sollicitudin erat, id faucibus nisi hendrerit quis. Praesent eleifend dui neque, ut ornare est malesuada ut. Ut ut vestibulum justo. Quisque quis ornare urna. Nullam mollis tristique felis vel lobortis. Suspendisse fermentum diam mi, vel consectetur nisi scelerisque sed. Proin auctor eget est eget congue.</p>
			<p>Nunc non lectus risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce pellentesque sagittis vulputate. Vivamus leo nisl, blandit suscipit condimentum congue, condimentum dignissim leo. Nullam sodales pulvinar auctor. Sed vel nibh metus. Nam a accumsan nisl./p>
			<p>Fusce fringilla purus vitae sollicitudin mollis. Ut mollis tincidunt ante sit amet luctus. Mauris eu ante feugiat turpis auctor fringilla. Ut eu orci vehicula, adipiscing nunc ac, accumsan libero. Ut et ultrices felis. Curabitur facilisis, leo nec tincidunt vulputate, erat purus porta urna, eget iaculis quam lorem eu sem. Sed scelerisque tellus quis ultricies elementum. Phasellus nisl mauris, fringilla bibendum gravida ut, consequat vitae quam. Proin ligula velit, dapibus eu arcu a, malesuada aliquam eros. Pellentesque tortor eros, blandit ut lacus a, ultricies feugiat velit.</p>
			<p>Aenean porta rhoncus nunc, nec vestibulum odio convallis quis. Proin turpis enim, rutrum ut lacinia non, pharetra eu ligula. Praesent posuere, tortor a scelerisque iaculis, magna ante aliquam orci, et gravida tellus quam quis felis. Nulla facilisi. Cras velit felis, elementum ut dolor at, tincidunt facilisis augue. Aliquam erat volutpat. Aenean nec quam metus. Quisque mattis sem vitae eros condimentum iaculis. Suspendisse quis semper mi. Suspendisse porta, ipsum in congue varius, enim risus semper quam, ac gravida nisi sem vel augue. Sed fermentum pharetra nibh ac fermentum. Pellentesque non ornare augue. Curabitur vehicula odio ut urna rhoncus, a placerat magna porta. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
			<p>Aenean sodales, neque et commodo porta, arcu velit consectetur arcu, eget dignissim velit dui ultrices ligula. Cras ac nibh dolor. Nullam mollis rutrum auctor. Donec aliquam, magna at dignissim aliquam, est quam iaculis arcu, at semper lorem erat ut nulla. Suspendisse potenti. Phasellus semper vestibulum erat, suscipit dictum quam consectetur vitae. Phasellus tempor, nisi sed suscipit porta, magna magna elementum ipsum, id ultrices ante nisi eu risus. Donec aliquam elit a lorem varius, ac rhoncus nibh volutpat.</p>
			<p>Phasellus ut turpis at tortor accumsan semper. Duis blandit, magna congue semper fermentum, quam justo sagittis metus, ut rhoncus erat nisi sed arcu. Phasellus in risus semper, convallis metus ut, imperdiet quam. Donec aliquam eget libero vitae venenatis. Quisque nec dictum ipsum, non mollis massa. Sed vestibulum gravida nisl, sit amet varius tortor rutrum quis. Aliquam blandit metus a varius tristique. Integer egestas ac diam at auctor. Nam congue pulviuam vel faucibus. Ut ac pellentesque erat, eu ultrices lacus. Praesent elit velit, ultricies nec pharetra at, fringilla non tellus. Integer nibh lectus, dignissim id placerat quis, ornare ut dui. Vestibulum sodales a est et sagittis. Nam tincidunt mattis turpis lobortis faucibus.</p>
			<p>Morbi laoreet rhoncus elit, sit amet aliquet justo mattis a. Donec id sodales mi, eget feugiat orci. Mauris ac iaculis mi. Duis vitae tempor ligula. Suspendisse luctus turpis eu enim interdum blandit. Fusce nec lobortis lectus. Donec rhoncus sagittis urna, quis vulputate justo ornare eu. Donec fringilla metus lobortis, commodo elit vel, aliquet tortor. In fermentum ultrices blandit. Phasellus commodo non quam eu tincidunt. Proin et molestie turpis. Nullased augue justo. Pellentesque hendrerit eros vel massa porta posuere. Ut faucibus pretium mauris quis semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum metus lectus, blandit a felis sit amet, volutpat pretium eros.</p>
			<p>Vivamus a sollicitudin tellus, et molestie nunc. Suspendisse rhoncus enim ante, quis cursus quam faucibus nec. Suspendisse potenti. Ut quis felis at purus faucibus pharetra. Aliquam erat volutpat. Praesent vestibulum nisi sit amet libero gravida porta. Etiam metus velit, dignissim vitae dignissim a, viverra vitae est. Duis imperdiet congue libero, id hendrerit tellus. Sed erat diam, porta facilisis massa eget, mattis hendrerit augue. Sed sed congue nisl.</p>
			<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque tristique pellentesque est, a tempus libero molestie eget. Phasellus feugiat velit ac est sollicitudin molestie. Curabitur nec risus nunc. Aliquam erat volutpat. Vestibulum egestas justo sed bibendum sodales. Pellentesque id felis risus. Pellentesque euismod quis massa sed consectetur. Mauris at tempor urna. Phasellus ullamcorper ante vitae auctor dictum. Aliquam ut sollicitudin ipsum. Aliquam vitae purus vel urna eleifend ultricies. Vestibulum commodo sed metus in pretium. Vestibulum consequat metus ac mi blandit, eget dapibus massa blandit. Sed eget lobortis massa.</p>
			
			<div class="news_foot">
				<span class="commentaire"><a href="">Commentaire</a></span>
				<span class="author">Publie par Op</span>
			</div>
			
		</div>	
		
		<div class="news">
			<h2><a href="">Lorem Ipsum</a></h2>
			<p class="date">Oct 26, 2013</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in eros sodales, fringilla mi eget, malesuada lacus. Cras sit amet urna quis nulla vestibulum porta. Integer massa massa, faucibus eget sapien at, fringilla porttitor elit. Praesent venenatis massa neque, ac iaculis elit aliquet ac. Curabitur eget tempus leo. Maecenas non velit non dui varius lacinia. Fusce id volutpat dui, in volutpat nibh. Nam nulla ligula, porta id ipsum vel, laoreet blandit felis. Duis et urna blandit, ullamcorper nisi ut, posuere erat. In adipiscing, elit sodales posuere semper, orci ligula convallis arcu, in malesuada felis orci a lorem. Nullam ultrices mauris sed mi porttitor vestibulum sit amet vitae justo. Proin vitae fermentum libero, a volutpat mauris. Maecenas eleifend scelerisque odio. Donec aliquet, massa non consectetur tincidunt, lacus lacus fermentum lorem, id adipiscing augue enim vel lectus. Duis molestie faucibus ipsum, non commodo erat laoreet feugiat.</p>
			<p>Nullam blandit sollicitudin erat, id faucibus nisi hendrerit quis. Praesent eleifend dui neque, ut ornare est malesuada ut. Ut ut vestibulum justo. Quisque quis ornare urna. Nullam mollis tristique felis vel lobortis. Suspendisse fermentum diam mi, vel consectetur nisi scelerisque sed. Proin auctor eget est eget congue.</p>
			<p>Nunc non lectus risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce pellentesque sagittis vulputate. Vivamus leo nisl, blandit suscipit condimentum congue, condimentum dignissim leo. Nullam sodales pulvinar auctor. Sed vel nibh metus. Nam a accumsan nisl./p>
			<p>Fusce fringilla purus vitae sollicitudin mollis. Ut mollis tincidunt ante sit amet luctus. Mauris eu ante feugiat turpis auctor fringilla. Ut eu orci vehicula, adipiscing nunc ac, accumsan libero. Ut et ultrices felis. Curabitur facilisis, leo nec tincidunt vulputate, erat purus porta urna, eget iaculis quam lorem eu sem. Sed scelerisque tellus quis ultricies elementum. Phasellus nisl mauris, fringilla bibendum gravida ut, consequat vitae quam. Proin ligula velit, dapibus eu arcu a, malesuada aliquam eros. Pellentesque tortor eros, blandit ut lacus a, ultricies feugiat velit.</p>
			<p>Aenean porta rhoncus nunc, nec vestibulum odio convallis quis. Proin turpis enim, rutrum ut lacinia non, pharetra eu ligula. Praesent posuere, tortor a scelerisque iaculis, magna ante aliquam orci, et gravida tellus quam quis felis. Nulla facilisi. Cras velit felis, elementum ut dolor at, tincidunt facilisis augue. Aliquam erat volutpat. Aenean nec quam metus. Quisque mattis sem vitae eros condimentum iaculis. Suspendisse quis semper mi. Suspendisse porta, ipsum in congue varius, enim risus semper quam, ac gravida nisi sem vel augue. Sed fermentum pharetra nibh ac fermentum. Pellentesque non ornare augue. Curabitur vehicula odio ut urna rhoncus, a placerat magna porta. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
			<p>Aenean sodales, neque et commodo porta, arcu velit consectetur arcu, eget dignissim velit dui ultrices ligula. Cras ac nibh dolor. Nullam mollis rutrum auctor. Donec aliquam, magna at dignissim aliquam, est quam iaculis arcu, at semper lorem erat ut nulla. Suspendisse potenti. Phasellus semper vestibulum erat, suscipit dictum quam consectetur vitae. Phasellus tempor, nisi sed suscipit porta, magna magna elementum ipsum, id ultrices ante nisi eu risus. Donec aliquam elit a lorem varius, ac rhoncus nibh volutpat.</p>
			<p>Phasellus ut turpis at tortor accumsan semper. Duis blandit, magna congue semper fermentum, quam justo sagittis metus, ut rhoncus erat nisi sed arcu. Phasellus in risus semper, convallis metus ut, imperdiet quam. Donec aliquam eget libero vitae venenatis. Quisque nec dictum ipsum, non mollis massa. Sed vestibulum gravida nisl, sit amet varius tortor rutrum quis. Aliquam blandit metus a varius tristique. Integer egestas ac diam at auctor. Nam congue pulviuam vel faucibus. Ut ac pellentesque erat, eu ultrices lacus. Praesent elit velit, ultricies nec pharetra at, fringilla non tellus. Integer nibh lectus, dignissim id placerat quis, ornare ut dui. Vestibulum sodales a est et sagittis. Nam tincidunt mattis turpis lobortis faucibus.</p>
			<p>Morbi laoreet rhoncus elit, sit amet aliquet justo mattis a. Donec id sodales mi, eget feugiat orci. Mauris ac iaculis mi. Duis vitae tempor ligula. Suspendisse luctus turpis eu enim interdum blandit. Fusce nec lobortis lectus. Donec rhoncus sagittis urna, quis vulputate justo ornare eu. Donec fringilla metus lobortis, commodo elit vel, aliquet tortor. In fermentum ultrices blandit. Phasellus commodo non quam eu tincidunt. Proin et molestie turpis. Nullased augue justo. Pellentesque hendrerit eros vel massa porta posuere. Ut faucibus pretium mauris quis semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum metus lectus, blandit a felis sit amet, volutpat pretium eros.</p>
			<p>Vivamus a sollicitudin tellus, et molestie nunc. Suspendisse rhoncus enim ante, quis cursus quam faucibus nec. Suspendisse potenti. Ut quis felis at purus faucibus pharetra. Aliquam erat volutpat. Praesent vestibulum nisi sit amet libero gravida porta. Etiam metus velit, dignissim vitae dignissim a, viverra vitae est. Duis imperdiet congue libero, id hendrerit tellus. Sed erat diam, porta facilisis massa eget, mattis hendrerit augue. Sed sed congue nisl.</p>
			<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque tristique pellentesque est, a tempus libero molestie eget. Phasellus feugiat velit ac est sollicitudin molestie. Curabitur nec risus nunc. Aliquam erat volutpat. Vestibulum egestas justo sed bibendum sodales. Pellentesque id felis risus. Pellentesque euismod quis massa sed consectetur. Mauris at tempor urna. Phasellus ullamcorper ante vitae auctor dictum. Aliquam ut sollicitudin ipsum. Aliquam vitae purus vel urna eleifend ultricies. Vestibulum commodo sed metus in pretium. Vestibulum consequat metus ac mi blandit, eget dapibus massa blandit. Sed eget lobortis massa.</p>
			
			<div class="news_foot">
				<a href="commentaires.php?id=1#commentaire">Commentaire</a>
				<span class="author">Publie par Op</span>
			</div>
			
		</div>	
<?php
include("footer.php");
?>